#!/bin/bash

usage="Usage: $(basename $0) [-h]
    -h - help
    -a - [256] application name
    -e - [1024] event name
    -d - [10000] description of the event
    -u - [512] url of application
Post to prowl
"

KEY_FILE="${HOME}/.prowlnotify/.prowlapikey"

if [ ! -e ${KEY_FILE} ]; then
  echo "Prowl API Key needs to be present in file [${KEY_FILE}]"
  exit 1
fi

apikey=$(cat ~/.prowlnotify/.prowlapikey | head -1)
application_name=
event_name=
description=
url=
while [ $# -gt 0 ]; do
    case "$1" in
        -h|-\?)
            echo "$usage"
            exit 0
        ;;
        -a)
        	application_name="$2"
        	shift
        ;;
        -e)
        	event_name="$2"
        	shift
        ;;
        -d)
        	description="$2"
        	shift
        ;;
        -u)
        	url="$2"
        	shift
        ;;
        -*)
             echo "Error: unexpected option: $1" 1>&2
             exit 1
        ;;
        *)
            break
        ;;
    esac
    shift
done

if [ -z "${application_name:-}" ]; then
  echo "Application name should be set with the -a parameter."
  echo ""
  echo "$usage"
  exit 1
fi
if [ -z "${event_name:-}" ]; then
  echo "Event name should be set with the -e parameter."
  echo ""
  echo "$usage"
  exit 1
fi
if [ -z "${description:-}" ]; then
  echo "Description should be set with the -d parameter."
  echo ""
  echo "$usage"
  exit 1
fi

if [ -z "${url:-}" ]; then
  curl -d "apikey=${apikey}" -d "application=${application_name}" -d "event=${event_name}" -d "description=${description}" -X POST "https://api.prowlapp.com/publicapi/add"
else
  curl -d "apikey=${apikey}" -d "application=${application_name}" -d "event=${event_name}" -u "url=${url}" -d "description=${description}" -X POST "https://api.prowlapp.com/publicapi/add"
fi
